import { createSlice } from '@reduxjs/toolkit'

const filterSlice = createSlice({
    name: 'filter',
    initialState: [],
    reducers: {
        filterChange: (state, action) => {
            return action.payload
        }
    }
})

// Export the action creator generated by createSlice
export const { filterChange } = filterSlice.actions

// Export the reducer to be used in the store
export default filterSlice.reducer
